import type { MaterialDefinition } from "./material-definition.js";
import { StressStrainCurve } from "./stress-strain-curve/stress-strain-curve.js";

const defaultSolid = {
    friction: 0.5,
    compliance: 1e-8,
    normalScale: 1,
    occlusionStrength: 1,
    baseColorUrl: "",
    metallicRoughnessUrl: "",
    normalUrl: "",
    occlusionUrl: "",
    emissiveUrl: "",
} as const satisfies Partial<MaterialDefinition>;

const noSolidCurve = {
    stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0,0],
            tensileFractureStrainStress: [0,0],
            compressiveYieldStrainStress: [0,0],
            compressiveFractureStrainStress: [0,0],
        }),
};

const metaMaterialBase: Omit<MaterialDefinition, "baseColorFactor"> = {
    metallicFactor: 0.8,
    roughnessFactor: 0.2,
    irReflectance: 0.5,
    irEmission: 0,
    emissionMode: 0,
    restitution: 0.35,
    emissiveFactor: [0, 0, 0],
    density: 1200,
    viscosity: 0,
    heatCapacity: Number.POSITIVE_INFINITY,
    thermalConductivity: 100,
    ...defaultSolid,
    stressStrainCurve: StressStrainCurve.create({
        tensileYieldStrainStress: [0.01333, 40],
        tensileFractureStrainStress: [0.08, 48],
        compressiveYieldStrainStress: [-0.015, -45],
        compressiveFractureStrainStress: [-0.09, -52],
    }),
};

export const definitions = {
    air: {
        baseColorFactor: [1,1,1,0],
                metallicFactor: 0,
        roughnessFactor: 0,
        irReflectance: 0,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0,
        emissiveFactor: [0,0,0],
        density: 1.225,
        viscosity: 0,
        heatCapacity: 1006,
        thermalConductivity: 0.024,
        ...defaultSolid,
        ...noSolidCurve,
    },
    water: {
        baseColorFactor: [0,0,1,0.1],
                metallicFactor: 0,
        roughnessFactor: 0,
        irReflectance: 0,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.05,
        emissiveFactor: [0,0,0],
        density: 997,
        viscosity: 1,
        heatCapacity: 4200,
        thermalConductivity: 0.66,
        ...defaultSolid,
        ...noSolidCurve,
    },
    rock: {
        baseColorFactor: [0.5,0.5,0.5,1],
                metallicFactor: 0,
        roughnessFactor: 0.8,
        irReflectance: 0.1,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.15,
        emissiveFactor: [0,0,0],
        density: 2650,
        viscosity: 0,
        heatCapacity: 800,
        thermalConductivity: 4,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.0016,80],
            tensileFractureStrainStress: [0.002,90],
            compressiveYieldStrainStress: [-0.0026,-130],
            compressiveFractureStrainStress: [-0.004,-160],
        }),
    },
    ice: {
        baseColorFactor: [0.8,0.8,1,0.5],
                metallicFactor: 0,
        roughnessFactor: 0.1,
        irReflectance: 0.2,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.2,
        emissiveFactor: [0,0,0],
        density: 917,
        viscosity: 0,
        heatCapacity: 2040,
        thermalConductivity: 2.18,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.00156,15],
            tensileFractureStrainStress: [0.002,18],
            compressiveYieldStrainStress: [-0.00365,-35],
            compressiveFractureStrainStress: [-0.005,-45],
        }),
    },
    iron: {
        baseColorFactor: [0.7,0.7,0.7,1],
                metallicFactor: 1,
        roughnessFactor: 0.3,
        irReflectance: 0.4,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.45,
        emissiveFactor: [0,0,0],
        density: 7874,
        viscosity: 0,
        heatCapacity: 460,
        thermalConductivity: 50,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.001,200],
            tensileFractureStrainStress: [0.12,350],
            compressiveYieldStrainStress: [-0.0011,-220],
            compressiveFractureStrainStress: [-0.11,-400],
        }),
    },
    dirt: {
        baseColorFactor: [0.4,0.3,0.2,1],
                metallicFactor: 0,
        roughnessFactor: 0.9,
        irReflectance: 0.05,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.05,
        emissiveFactor: [0,0,0],
        density: 1510,
        viscosity: 0,
        heatCapacity: 800,
        thermalConductivity: 0.25,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.04,2],
            tensileFractureStrainStress: [0.08,4],
            compressiveYieldStrainStress: [-0.12,-6],
            compressiveFractureStrainStress: [-0.2,-10],
        }),
    },
    sand: {
        baseColorFactor: [0.9,0.8,0.6,1],
                metallicFactor: 0,
        roughnessFactor: 0.8,
        irReflectance: 0.1,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.15,
        emissiveFactor: [0,0,0],
        density: 2100,
        viscosity: 0,
        heatCapacity: 830,
        thermalConductivity: 0.2,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.0125,1],
            tensileFractureStrainStress: [0.025,2],
            compressiveYieldStrainStress: [-0.05,-4],
            compressiveFractureStrainStress: [-0.09,-7],
        }),
    },
    woodHard: {
        baseColorFactor: [0.6,0.4,0.2,1],
                metallicFactor: 0,
        roughnessFactor: 0.7,
        irReflectance: 0.05,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.3,
        emissiveFactor: [0,0,0],
        density: 650,
        viscosity: 0,
        heatCapacity: 2000,
        thermalConductivity: 0.16,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.00375,45],
            tensileFractureStrainStress: [0.04,52],
            compressiveYieldStrainStress: [-0.0048,-58],
            compressiveFractureStrainStress: [-0.055,-68],
        }),
    },
    woodSoft: {
        baseColorFactor: [0.7,0.5,0.3,1],
                metallicFactor: 0,
        roughnessFactor: 0.8,
        irReflectance: 0.05,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.28,
        emissiveFactor: [0,0,0],
        density: 490,
        viscosity: 0,
        heatCapacity: 2300,
        thermalConductivity: 0.12,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.00389,35],
            tensileFractureStrainStress: [0.045,42],
            compressiveYieldStrainStress: [-0.00489,-44],
            compressiveFractureStrainStress: [-0.055,-54],
        }),
    },
    steel: {
        baseColorFactor: [0.55,0.55,0.6,1],
                metallicFactor: 1,
        roughnessFactor: 0.2,
        irReflectance: 0.3,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.55,
        emissiveFactor: [0,0,0],
        density: 7850,
        viscosity: 0,
        heatCapacity: 490,
        thermalConductivity: 50,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.00175,350],
            tensileFractureStrainStress: [0.15,500],
            compressiveYieldStrainStress: [-0.0019,-380],
            compressiveFractureStrainStress: [-0.13,-520],
        }),
    },
    concrete: {
        baseColorFactor: [0.6,0.6,0.6,1],
                metallicFactor: 0,
        roughnessFactor: 0.9,
        irReflectance: 0.1,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.12,
        emissiveFactor: [0,0,0],
        density: 2400,
        viscosity: 0,
        heatCapacity: 880,
        thermalConductivity: 1.4,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.000117,3.5],
            tensileFractureStrainStress: [0.00015,4],
            compressiveYieldStrainStress: [-0.00117,-35],
            compressiveFractureStrainStress: [-0.003,-40],
        }),
    },
    reinforcedConcrete: {
        baseColorFactor: [0.55,0.55,0.55,1],
                metallicFactor: 0.1,
        roughnessFactor: 0.9,
        irReflectance: 0.15,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.14,
        emissiveFactor: [0,0,0],
        density: 2500,
        viscosity: 0,
        heatCapacity: 880,
        thermalConductivity: 2,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.00015,4.5],
            tensileFractureStrainStress: [0.00022,5.5],
            compressiveYieldStrainStress: [-0.0015,-45],
            compressiveFractureStrainStress: [-0.0035,-55],
        }),
    },
    glass: {
        baseColorFactor: [0.9,0.95,1,0.3],
                metallicFactor: 0,
        roughnessFactor: 0.05,
        irReflectance: 0.1,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.18,
        emissiveFactor: [0,0,0],
        density: 2500,
        viscosity: 0,
        heatCapacity: 840,
        thermalConductivity: 1,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.00043,30],
            tensileFractureStrainStress: [0.0007,35],
            compressiveYieldStrainStress: [-0.005,-350],
            compressiveFractureStrainStress: [-0.006,-400],
        }),
    },
    temperedGlass: {
        baseColorFactor: [0.5,0.55,0.6,0.4],
                metallicFactor: 0,
        roughnessFactor: 0.05,
        irReflectance: 0.15,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.22,
        emissiveFactor: [0,0,0],
        density: 2500,
        viscosity: 0,
        heatCapacity: 840,
        thermalConductivity: 1,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.00171,120],
            tensileFractureStrainStress: [0.004,200],
            compressiveYieldStrainStress: [-0.00786,-550],
            compressiveFractureStrainStress: [-0.0095,-620],
        }),
    },
    meta: {
        ...metaMaterialBase,
        baseColorFactor: [0.2,0.6,0.7,1],
    },
    marble: {
        baseColorFactor: [0.9,0.9,0.9,1],
                metallicFactor: 0,
        roughnessFactor: 0.3,
        irReflectance: 0.2,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.12,
        emissiveFactor: [0,0,0],
        density: 2700,
        viscosity: 0,
        heatCapacity: 830,
        thermalConductivity: 1.4,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.000455,25],
            tensileFractureStrainStress: [0.00065,30],
            compressiveYieldStrainStress: [-0.00173,-95],
            compressiveFractureStrainStress: [-0.00273,-125],
        }),
    },
    granite: {
        baseColorFactor: [0.8,0.8,0.8,1],
                metallicFactor: 0,
        roughnessFactor: 0.6,
        irReflectance: 0.15,
        irEmission: 0,
        emissionMode: 0,
        restitution: 0.12,
        emissiveFactor: [0,0,0],
        density: 2700,
        viscosity: 0,
        heatCapacity: 830,
        thermalConductivity: 1.4,
        stressStrainCurve: StressStrainCurve.create({
            tensileYieldStrainStress: [0.00222,100],
            tensileFractureStrainStress: [0.0032,120],
            compressiveYieldStrainStress: [-0.00422,-190],
            compressiveFractureStrainStress: [-0.00555,-230],
        }),
    },
    metaRed: {
        ...metaMaterialBase,
        baseColorFactor: [1,0,0,1],
    },
    metaOrange: {
        ...metaMaterialBase,
        baseColorFactor: [1,0.5,0,1],
    },
    metaYellow: {
        ...metaMaterialBase,
        baseColorFactor: [1,1,0,1],
    },
    metaLime: {
        ...metaMaterialBase,
        baseColorFactor: [0.5,1,0,1],
    },
    metaGreen: {
        ...metaMaterialBase,
        baseColorFactor: [0,1,0,1],
    },
    metaTeal: {
        ...metaMaterialBase,
        baseColorFactor: [0,1,0.5,1],
    },
    metaCyan: {
        ...metaMaterialBase,
        baseColorFactor: [0,1,1,1],
    },
    metaBlue: {
        ...metaMaterialBase,
        baseColorFactor: [0,0.5,1,1],
    },
    metaIndigo: {
        ...metaMaterialBase,
        baseColorFactor: [0.25,0,1,1],
    },
    metaViolet: {
        ...metaMaterialBase,
        baseColorFactor: [0.5,0,1,1],
    },
    metaPurple: {
        ...metaMaterialBase,
        baseColorFactor: [0.75,0,1,1],
    },
    metaMagenta: {
        ...metaMaterialBase,
        baseColorFactor: [1,0,1,1],
    },
    metaPink: {
        ...metaMaterialBase,
        baseColorFactor: [1,0.5,0.75,1],
    },
    metaWhite: {
        ...metaMaterialBase,
        baseColorFactor: [1,1,1,1],
    },
    metaGray: {
        ...metaMaterialBase,
        baseColorFactor: [0.5,0.5,0.5,1],
    },
    metaBlack: {
        ...metaMaterialBase,
        baseColorFactor: [0,0,0,1],
    },
} as const satisfies Record<string, Partial<MaterialDefinition>>;
